trigger:
  - ci-devel

pool:
  vmImage: ubuntu-latest

stages:
  - stage: test_and_build
    displayName: Test and Build
    jobs:
      - job: test
        displayName: Run Tests
        steps:
          - script: |
              docker build -f Dockerfile.test -t testing .
              docker run -v $(Build.SourcesDirectory):/build testing pytest --disable-warnings --junitxml test-score.xml
            displayName: Run Unit Tests