trigger:
  - ci-devel

resources:
  containers:
    - container: conda
      image: continuumio/miniconda
      options: -v /home/vsts/env/mlops-demo:/env/mlops-demo
      env:
        SP_SECRET: $(SP_SECRET)
        ACCOUNT_KEY: $(ACCOUNT_KEY)
      mapDockerSocket: true

stages:
  - stage: test_and_build
    displayName: Test and Build
    jobs:
      - job: test
        displayName: Run Tests
        container: conda
        steps:
          - script: |
              conda env create -f environment.yaml -p /env/mlops-demo
              source activate /env/mlops-demo


