trigger:
  - ci-devel

pool:
  vmImage: ubuntu-latest

variables:
  - group: build-secrets

stages:
  - stage: test_and_deploy
    displayName: Test and Deploy
    jobs:
      - job: test
        displayName: Run Tests
        steps:
          - script: |
              docker build -f Dockerfile.test -t testing .
              docker run -v $(Build.SourcesDirectory):/build testing pytest --disable-warnings --junitxml test-score.xml
            displayName: Run Unit Tests
          
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: test-*.xml

          - script: |
              docker run -v $(Build.SourcesDirectory):/build python build.py
            env:
              SP_SECRET: $(SP_SECRET)