
name: Model Training Test

trigger:
  branches:
    include:
      - train-model

pool:
  vmImage: ubuntu-latest

variables:
  - group: build-secrets

container:
  image: python:3.7-slim

steps:
  - script: |
      pip install --user PyYAML
      python pipeline.py
    displayName: Train Model