
name: Model Training Test

trigger:
  branches:
    include:
      - train-model

pool:
  vmImage: ubuntu-latest

variables:
  - group: build-secrets

container:
  image: python:3.7-slim

steps:
  - script: echo "foo"
  # - script: |
  #     python pipeline.py
  #   displayName: Train Model
  #   target:
  #     container: AzureMLPy
    