
name: Model Training Test

trigger:
  branches:
    include:
      - train-model

variables:
  - group: build-secrets
jobs:
  - job: test
    displayName: Test Job
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: TAG=`git tag -l --points-at HEAD` && echo "##vso[task.setvariable variable=TAG]$TAG"
        displayName: Set the tag name as an environment variable
      
      - script: echo "training model $(TAG)"
        condition: startsWith(variables['TAG'], 'train')

  # - script: |
  #     pip install --user PyYAML azureml-sdk==1.0.81
  #     python pipeline.py
  #   displayName: Train Model
  #   env:
  #     SP_SECRET: $(SP_SECRET)
  #     ACCOUNT_KEY: $(ACCOUNT_KEY)
  #  foo 