
name: Model Training Test

trigger:
  branches:
    include:
      - train-model

variables:
  - group: build-secrets
jobs:
  - job: test
    displayName: Test Job
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
        displayName: Set the tag name as an environment variable
      
      - script: echo "training model $(VERSION_TAG)"
        condition: startsWith(variables['VERSION_TAG'], 'v1.0')

  # - script: |
  #     pip install --user PyYAML azureml-sdk==1.0.81
  #     python pipeline.py
  #   displayName: Train Model
  #   env:
  #     SP_SECRET: $(SP_SECRET)
  #     ACCOUNT_KEY: $(ACCOUNT_KEY)