  #Training conda dependencies
  - name: diabetes_training
    dependencies:
      - python = 3.7.5
      - numpy = 1.18.1
      - pandas = 1.0.0
      - scikit-learn = 0.22.1
      - pip = 20.0.2
      - pip:
        - azureml-core==1.0.79