trigger:
  branches:
    include:
      - master
  paths:
    include:
      - $(Build.SourcesDirectory)/arm-templates/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - $(Build.SourcesDirectory)/arm-templates/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: $(Build.SourcesDirectory)/azure-variables.yaml

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "$(variables.SUBSCRIPTION_ID)"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(variables.RESOURCE_GROUP)"
      templateLocation: "Linked artifact"
      location: $(variables.LOCATION_ID)
      csmFile: "$(Build.SourcesDirectory)/arm-templates/cloud-environment.json"
      overrideParameters: "-baseName $(variables.BASE_NAME) -location $(variables.LOCATION_ID)"
      deploymentMode: "Incremental"
      displayName: "Deploy MLOps resources to Azure"