trigger:
  branches:
    include:
      - master
  paths:
    include:
      - /arm-templates/*
pr:
  branches:
    include:
      - master
  paths:
    include:
      - /arm-templates/*

pool:
  vmImage: "ubuntu-latest"

variables:
  - template: /azure-variables.yaml

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: "AzureServiceConnection"
      action: "Create Or Update Resource Group"
      resourceGroupName: "$(RESOURCE_GROUP)"
      templateLocation: "Linked artifact"
      location: $(LOCATION_ID)
      csmFile: "$(Build.SourcesDirectory)/arm-templates/cloud-environment.json"
      overrideParameters: "-baseName $(BASE_NAME) -location $(LOCATION_ID)"
      deploymentMode: "Incremental"
      displayName: "Deploy MLOps resources to Azure"