pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - scripts/

  variables:
  - template: azure-variables.yml

  pool:
    vmImage: ubuntu-latest
  
  stages:

  - stage: 'Trigger_AML_Pipeline'
    displayName: 'Train model'
    jobs:
    - job: 'Get_Pipeline_ID'
      displayName: "Get Pipeline ID for execution"
      timeoutInMinutes: 0
      steps:
      - task: AzureCLI@2
      