pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - scripts/

variables:
- template: /variables.yml

pool:
  vmImage: ubuntu-latest
  
stages:

- stage: 'Trigger_AML_Pipeline'
  displayName: 'Train model'
  jobs:
  - job: 'Deploy AML pipeline'
    displayName: "Deploy AML pipeline"
    container: mcr.microsoft.com/mlops/python:latest
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AML_WORKSPACE_SERVICE_CONNECTION)
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          python3 $(AML_PIPELINE_PATH)
            

            

      